--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/PvPToggle
build-by-default: true
branches:
- master
projects:
  PvPToggle:
    path: ""
    libs:
      - src: JackMD/UpdateNotifier/UpdateNotifier
        version: ^2.1
...
