name: PvPToggle
main: brokiem\pvptoggle\PvPToggle

version: 1.0.0
api: 3.10.0

author: brokiem

commands:
  pvp:
    description: toggle pvp
    permission: pvptoggle.pvp

permissions:
  pvptoggle.pvp:
    default: true
  pvptoggle.staff:
    default: op